### ISSUE TITLE
examples link broken

### ISSUE THREAD

**Issue by Klar** [BuxOrg/bux-server#109]
### What's your question?

Example links are broken, not sure where the examples are?

- https://github.com/BuxOrg/bux-server/blob/0b480a2d20f68565c171241ca5f537d697da2593/README.md?plain=1#L226
- https://github.com/BuxOrg/bux-server/blob/0b480a2d20f68565c171241ca5f537d697da2593/README.md?plain=1#L265

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrz1836** [comment]
@Klar if you want to add an example - feel free to do so - otherwise I will remove the links for now.
