### ISSUE TITLE
[Feature]: Move bux console into server

### ISSUE THREAD

**Issue by icellan** [BuxOrg/bux-server#180]
### What's the feature

Console should be in server

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrz1836** [comment]
@icellan Why?

We could add a different install method to bring it in if needed?

**Comment by icellan** [comment]
@mrz1836 This is a ticket referencing the branch we already worked on trying to get a clean console into the server, to make it easier to run a console, if you want. It will all be integrated into the Go runtime and can be turned off via config.

https://github.com/BuxOrg/bux-server/tree/siggi/console-integrated
