### ISSUE TITLE
[Bug]: Docker compose doesn't work

### ISSUE THREAD

**Issue by golangdaddy** [BuxOrg/bux-server#70]
### What happened?

Race condition between server and database resulting in server failing.

I added a time.Sleep, then it failed because it couldn't find a websocket agent on port 8000.

Please advise.

### How can we reproduce this?

run docker-compose

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrz1836** [comment]
@galt-tr can you take a look at this?
